### ISSUE TITLE
Players are marked as barbarians but also in a kingdom. Unable to join/leave since they are locked in.

### ISSUE THREAD

**Issue by MidnightSoul933** [Rumsfield/konquest#137] opened 2023-09-09 09:06 UTC
**Bug Description**
> hi. my players show up as barbarians but they are still listed as in their respective kingdoms. They cannot build or interact in their own kingdoms lands since the game says they are not in that kingdom but they also cannot join or leave a kingdom since they are also classified as barbarians. What do you recommend to do?

**Steps To Reproduce**
> Im not sure, One day it showed up like this.

**Versions (please complete the following information):**
 - Konquest:
 - Paper: 1.20

**Config File(s)**
[konquestBackup.zip](https://github.com/Rumsfield/konquest/files/12565369/konquestBackup.zip)

**Comment by Rumsfield** [comment] 2023-09-09 20:18
Hi, thanks for reporting this issue. I'll look for ways to improve the plugin so that this does not happen again.

I suspect that the cause of this problem is related to your MySQL database. Some player data (which kingdom they're in, whether they're a barbarian or not) is stored in the Konquest database - MySQL or SQLite (default). When a player joins the server, the plugin requests that player's info from the database. If the database connection has been lost for some reason, or the data has been corrupted, then it's possible that the plugin will think the player is new to the server and will treat them as a barbarian.

Each kingdom, on the other hand, remembers the UUIDs of all members locally within the `kingdoms.yml` data file. So each kingdom might appear to keep these "barbarian" players as members.

So I suspect the root cause could lie in your MySQL database. Are the credentials in `core.yml` correct, and the connection to the database is solid? Try checking that first. Did you recently change from the default SQLite to MySQL? If so, then all of the player data in the default SQLite database file `Konquest.db` will **not** be transferred to the new MySQL database.

I recommend that you review your database settings and connections, and then possibly revert to a previous backup of your Konquest plugin files, see [`backup-instructions-readme.txt`](https://github.com/Rumsfield/konquest/blob/main/core/src/main/resources/backup-instructions-readme.txt).

**Closed** 2023-11-05 23:40 UTC
Labels: bug
